version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sapassword@123
      - MSSQL_DATABASE=msdb
    ports:
      - "1433:1433"
  product-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mssql
    environment:
      - MSSQL_HOST=mssql
      - MSSQL_PORT=1433
      - MSSQL_DATABASE=msdb
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=Sapassword@123