spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
          filters:
            - AuthenticationFilter
        - id: orders-service
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**
          filters:
            - AuthenticationFilter
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**

